// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package sqlcdb

import (
	"context"
)

const getActiveTasks = `-- name: GetActiveTasks :many
SELECT t.id, t.title, t.deadline, t.status, t.category, t.project_id, p.name AS project_name,
    CASE WHEN t.deadline < date('now') AND t.status NOT IN ('done','cancelled') THEN 1 ELSE 0 END AS is_overdue
FROM tasks t
JOIN projects p ON p.id = t.project_id
WHERE t.status NOT IN ('done','cancelled')
ORDER BY t.deadline ASC
`

type GetActiveTasksRow struct {
	ID          int64
	Title       string
	Deadline    string
	Status      string
	Category    string
	ProjectID   int64
	ProjectName string
	IsOverdue   int64
}

func (q *Queries) GetActiveTasks(ctx context.Context) ([]GetActiveTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveTasksRow{}
	for rows.Next() {
		var i GetActiveTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Deadline,
			&i.Status,
			&i.Category,
			&i.ProjectID,
			&i.ProjectName,
			&i.IsOverdue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardProjects = `-- name: GetDashboardProjects :many
SELECT p.id, p.name, p.priority, p.status,
    COALESCE((SELECT COUNT(*) FROM tasks t WHERE t.project_id = p.id AND t.status NOT IN ('done','cancelled')), 0) AS task_count,
    COALESCE((SELECT COUNT(*) FROM tasks t WHERE t.project_id = p.id AND t.deadline < date('now') AND t.status NOT IN ('done','cancelled')), 0) AS overdue_count
FROM projects p
WHERE p.status = 'active'
ORDER BY p.priority ASC, p.name ASC
`

type GetDashboardProjectsRow struct {
	ID           int64
	Name         string
	Priority     int64
	Status       string
	TaskCount    interface{}
	OverdueCount interface{}
}

func (q *Queries) GetDashboardProjects(ctx context.Context) ([]GetDashboardProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDashboardProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDashboardProjectsRow{}
	for rows.Next() {
		var i GetDashboardProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Priority,
			&i.Status,
			&i.TaskCount,
			&i.OverdueCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingMeetings = `-- name: GetUpcomingMeetings :many
SELECT m.id, m.title, m.date, m.project_id, p.name AS project_name
FROM meetings m
JOIN projects p ON p.id = m.project_id
WHERE m.date BETWEEN date('now') AND date('now', '+7 days')
ORDER BY m.date ASC
`

type GetUpcomingMeetingsRow struct {
	ID          int64
	Title       string
	Date        string
	ProjectID   int64
	ProjectName string
}

func (q *Queries) GetUpcomingMeetings(ctx context.Context) ([]GetUpcomingMeetingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingMeetings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUpcomingMeetingsRow{}
	for rows.Next() {
		var i GetUpcomingMeetingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Date,
			&i.ProjectID,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
