// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meetings.sql

package sqlcdb

import (
	"context"
)

const addMeetingParticipant = `-- name: AddMeetingParticipant :exec
INSERT OR IGNORE INTO meeting_participants (meeting_id, person_id) VALUES (?, ?)
`

type AddMeetingParticipantParams struct {
	MeetingID int64
	PersonID  int64
}

func (q *Queries) AddMeetingParticipant(ctx context.Context, arg AddMeetingParticipantParams) error {
	_, err := q.db.ExecContext(ctx, addMeetingParticipant, arg.MeetingID, arg.PersonID)
	return err
}

const createMeeting = `-- name: CreateMeeting :execlastid
INSERT INTO meetings (project_id, date, meeting_type, title, notes) VALUES (?, ?, ?, ?, ?)
`

type CreateMeetingParams struct {
	ProjectID   int64
	Date        string
	MeetingType string
	Title       string
	Notes       string
}

func (q *Queries) CreateMeeting(ctx context.Context, arg CreateMeetingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createMeeting,
		arg.ProjectID,
		arg.Date,
		arg.MeetingType,
		arg.Title,
		arg.Notes,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteMeeting = `-- name: DeleteMeeting :exec
DELETE FROM meetings WHERE id = ?
`

func (q *Queries) DeleteMeeting(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMeeting, id)
	return err
}

const getMeetingByID = `-- name: GetMeetingByID :one
SELECT m.id, m.project_id, m.date, m.meeting_type, m.title, m.notes,
    m.created_at, m.updated_at, p.name AS project_name
FROM meetings m
JOIN projects p ON p.id = m.project_id
WHERE m.id = ?
`

type GetMeetingByIDRow struct {
	ID          int64
	ProjectID   int64
	Date        string
	MeetingType string
	Title       string
	Notes       string
	CreatedAt   string
	UpdatedAt   string
	ProjectName string
}

func (q *Queries) GetMeetingByID(ctx context.Context, id int64) (GetMeetingByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMeetingByID, id)
	var i GetMeetingByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Date,
		&i.MeetingType,
		&i.Title,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectName,
	)
	return i, err
}

const getMeetingParticipants = `-- name: GetMeetingParticipants :many
SELECT pe.id, pe.name, pe.company, pe.role, COALESCE(pe.email,'') AS email, COALESCE(pe.phone,'') AS phone,
    pe.person_type
FROM meeting_participants mp
JOIN people pe ON pe.id = mp.person_id
WHERE mp.meeting_id = ?
ORDER BY pe.name
`

type GetMeetingParticipantsRow struct {
	ID         int64
	Name       string
	Company    string
	Role       string
	Email      string
	Phone      string
	PersonType string
}

func (q *Queries) GetMeetingParticipants(ctx context.Context, meetingID int64) ([]GetMeetingParticipantsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMeetingParticipants, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMeetingParticipantsRow{}
	for rows.Next() {
		var i GetMeetingParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Company,
			&i.Role,
			&i.Email,
			&i.Phone,
			&i.PersonType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeetings = `-- name: ListMeetings :many
SELECT m.id, m.project_id, m.date, m.meeting_type, m.title, m.notes,
    m.created_at, m.updated_at, p.name AS project_name
FROM meetings m
JOIN projects p ON p.id = m.project_id
WHERE (?1 IS NULL OR m.project_id = ?1)
  AND (?2 IS NULL OR m.date >= ?2)
  AND (?3 IS NULL OR m.date <= ?3)
ORDER BY m.date DESC
`

type ListMeetingsParams struct {
	ProjectID interface{}
	DateFrom  interface{}
	DateTo    interface{}
}

type ListMeetingsRow struct {
	ID          int64
	ProjectID   int64
	Date        string
	MeetingType string
	Title       string
	Notes       string
	CreatedAt   string
	UpdatedAt   string
	ProjectName string
}

func (q *Queries) ListMeetings(ctx context.Context, arg ListMeetingsParams) ([]ListMeetingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMeetings, arg.ProjectID, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMeetingsRow{}
	for rows.Next() {
		var i ListMeetingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Date,
			&i.MeetingType,
			&i.Title,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeetingsByProject = `-- name: ListMeetingsByProject :many
SELECT m.id, m.project_id, m.date, m.meeting_type, m.title, m.notes,
    m.created_at, m.updated_at, p.name AS project_name
FROM meetings m
JOIN projects p ON p.id = m.project_id
WHERE m.project_id = ?
ORDER BY m.date DESC
`

type ListMeetingsByProjectRow struct {
	ID          int64
	ProjectID   int64
	Date        string
	MeetingType string
	Title       string
	Notes       string
	CreatedAt   string
	UpdatedAt   string
	ProjectName string
}

func (q *Queries) ListMeetingsByProject(ctx context.Context, projectID int64) ([]ListMeetingsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listMeetingsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMeetingsByProjectRow{}
	for rows.Next() {
		var i ListMeetingsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Date,
			&i.MeetingType,
			&i.Title,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMeetingParticipant = `-- name: RemoveMeetingParticipant :exec
DELETE FROM meeting_participants WHERE meeting_id = ? AND person_id = ?
`

type RemoveMeetingParticipantParams struct {
	MeetingID int64
	PersonID  int64
}

func (q *Queries) RemoveMeetingParticipant(ctx context.Context, arg RemoveMeetingParticipantParams) error {
	_, err := q.db.ExecContext(ctx, removeMeetingParticipant, arg.MeetingID, arg.PersonID)
	return err
}

const updateMeeting = `-- name: UpdateMeeting :exec
UPDATE meetings SET project_id=?, date=?, meeting_type=?, title=?, notes=? WHERE id=?
`

type UpdateMeetingParams struct {
	ProjectID   int64
	Date        string
	MeetingType string
	Title       string
	Notes       string
	ID          int64
}

func (q *Queries) UpdateMeeting(ctx context.Context, arg UpdateMeetingParams) error {
	_, err := q.db.ExecContext(ctx, updateMeeting,
		arg.ProjectID,
		arg.Date,
		arg.MeetingType,
		arg.Title,
		arg.Notes,
		arg.ID,
	)
	return err
}
