// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"database/sql"
)

type Meeting struct {
	ID          int64
	ProjectID   int64
	Date        string
	MeetingType string
	Title       string
	Notes       string
	CreatedAt   string
	UpdatedAt   string
}

type MeetingParticipant struct {
	MeetingID int64
	PersonID  int64
}

type Person struct {
	ID        int64
	Name      string
	Company   string
	Role      string
	Email     sql.NullString
	Phone     sql.NullString
	CreatedAt string
	UpdatedAt string
}

type Project struct {
	ID          int64
	Name        string
	Priority    int64
	StartDate   string
	EndDate     sql.NullString
	Status      string
	StaticInfo  string
	DynamicInfo string
	CreatedAt   string
	UpdatedAt   string
}

type ProjectPerson struct {
	ProjectID     int64
	PersonID      int64
	RoleInProject string
}

type Task struct {
	ID             int64
	ProjectID      int64
	MeetingID      sql.NullInt64
	Title          string
	StartDate      string
	Deadline       string
	EstimatedHours float64
	Status         string
	Category       string
	IsExternal     int64
	Description    string
	CreatedAt      string
	UpdatedAt      string
}

type TaskDependency struct {
	TaskID      int64
	DependsOnID int64
}
