// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: people.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const createPerson = `-- name: CreatePerson :execlastid
INSERT INTO people (name, company, role, email, phone, person_type) VALUES (?, ?, ?, ?, ?, ?)
`

type CreatePersonParams struct {
	Name       string
	Company    string
	Role       string
	Email      sql.NullString
	Phone      sql.NullString
	PersonType string
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createPerson,
		arg.Name,
		arg.Company,
		arg.Role,
		arg.Email,
		arg.Phone,
		arg.PersonType,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deletePerson = `-- name: DeletePerson :exec
DELETE FROM people WHERE id = ?
`

func (q *Queries) DeletePerson(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePerson, id)
	return err
}

const getPersonByID = `-- name: GetPersonByID :one
SELECT id, name, company, role, COALESCE(email,'') AS email, COALESCE(phone,'') AS phone, person_type, created_at, updated_at
FROM people WHERE id = ?
`

type GetPersonByIDRow struct {
	ID         int64
	Name       string
	Company    string
	Role       string
	Email      string
	Phone      string
	PersonType string
	CreatedAt  string
	UpdatedAt  string
}

func (q *Queries) GetPersonByID(ctx context.Context, id int64) (GetPersonByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPersonByID, id)
	var i GetPersonByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Company,
		&i.Role,
		&i.Email,
		&i.Phone,
		&i.PersonType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPeople = `-- name: ListPeople :many
SELECT id, name, company, role, COALESCE(email,'') AS email, COALESCE(phone,'') AS phone, person_type, created_at, updated_at
FROM people ORDER BY name ASC
`

type ListPeopleRow struct {
	ID         int64
	Name       string
	Company    string
	Role       string
	Email      string
	Phone      string
	PersonType string
	CreatedAt  string
	UpdatedAt  string
}

func (q *Queries) ListPeople(ctx context.Context) ([]ListPeopleRow, error) {
	rows, err := q.db.QueryContext(ctx, listPeople)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPeopleRow{}
	for rows.Next() {
		var i ListPeopleRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Company,
			&i.Role,
			&i.Email,
			&i.Phone,
			&i.PersonType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePerson = `-- name: UpdatePerson :exec
UPDATE people SET name=?, company=?, role=?, email=?, phone=?, person_type=? WHERE id=?
`

type UpdatePersonParams struct {
	Name       string
	Company    string
	Role       string
	Email      sql.NullString
	Phone      sql.NullString
	PersonType string
	ID         int64
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) error {
	_, err := q.db.ExecContext(ctx, updatePerson,
		arg.Name,
		arg.Company,
		arg.Role,
		arg.Email,
		arg.Phone,
		arg.PersonType,
		arg.ID,
	)
	return err
}
