// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const createProject = `-- name: CreateProject :execlastid
INSERT INTO projects (name, priority, start_date, end_date, status, static_info, dynamic_info)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateProjectParams struct {
	Name        string
	Priority    int64
	StartDate   string
	EndDate     sql.NullString
	Status      string
	StaticInfo  string
	DynamicInfo string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createProject,
		arg.Name,
		arg.Priority,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.StaticInfo,
		arg.DynamicInfo,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, priority, start_date, COALESCE(end_date,'') AS end_date, status,
    static_info, dynamic_info, created_at, updated_at
FROM projects WHERE id = ?
`

type GetProjectByIDRow struct {
	ID          int64
	Name        string
	Priority    int64
	StartDate   string
	EndDate     string
	Status      string
	StaticInfo  string
	DynamicInfo string
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) GetProjectByID(ctx context.Context, id int64) (GetProjectByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i GetProjectByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Priority,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.StaticInfo,
		&i.DynamicInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectPeople = `-- name: GetProjectPeople :many
SELECT pe.id, pe.name, pe.company, pe.role, COALESCE(pe.email,'') AS email, COALESCE(pe.phone,'') AS phone,
    pp.role_in_project
FROM project_people pp
JOIN people pe ON pe.id = pp.person_id
WHERE pp.project_id = ? ORDER BY pe.name
`

type GetProjectPeopleRow struct {
	ID            int64
	Name          string
	Company       string
	Role          string
	Email         string
	Phone         string
	RoleInProject string
}

func (q *Queries) GetProjectPeople(ctx context.Context, projectID int64) ([]GetProjectPeopleRow, error) {
	rows, err := q.db.QueryContext(ctx, getProjectPeople, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectPeopleRow{}
	for rows.Next() {
		var i GetProjectPeopleRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Company,
			&i.Role,
			&i.Email,
			&i.Phone,
			&i.RoleInProject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkPersonToProject = `-- name: LinkPersonToProject :exec
INSERT OR REPLACE INTO project_people (project_id, person_id, role_in_project) VALUES (?, ?, ?)
`

type LinkPersonToProjectParams struct {
	ProjectID     int64
	PersonID      int64
	RoleInProject string
}

func (q *Queries) LinkPersonToProject(ctx context.Context, arg LinkPersonToProjectParams) error {
	_, err := q.db.ExecContext(ctx, linkPersonToProject, arg.ProjectID, arg.PersonID, arg.RoleInProject)
	return err
}

const listActiveProjects = `-- name: ListActiveProjects :many
SELECT id, name, priority, start_date, COALESCE(end_date,'') AS end_date, status
FROM projects WHERE status = 'active'
ORDER BY priority ASC, name ASC
`

type ListActiveProjectsRow struct {
	ID        int64
	Name      string
	Priority  int64
	StartDate string
	EndDate   string
	Status    string
}

func (q *Queries) ListActiveProjects(ctx context.Context) ([]ListActiveProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveProjectsRow{}
	for rows.Next() {
		var i ListActiveProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Priority,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, priority, start_date, COALESCE(end_date,'') AS end_date, status,
    static_info, dynamic_info, created_at, updated_at
FROM projects ORDER BY priority ASC, name ASC
`

type ListProjectsRow struct {
	ID          int64
	Name        string
	Priority    int64
	StartDate   string
	EndDate     string
	Status      string
	StaticInfo  string
	DynamicInfo string
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) ListProjects(ctx context.Context) ([]ListProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Priority,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.StaticInfo,
			&i.DynamicInfo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkPersonFromProject = `-- name: UnlinkPersonFromProject :exec
DELETE FROM project_people WHERE project_id = ? AND person_id = ?
`

type UnlinkPersonFromProjectParams struct {
	ProjectID int64
	PersonID  int64
}

func (q *Queries) UnlinkPersonFromProject(ctx context.Context, arg UnlinkPersonFromProjectParams) error {
	_, err := q.db.ExecContext(ctx, unlinkPersonFromProject, arg.ProjectID, arg.PersonID)
	return err
}

const updateProject = `-- name: UpdateProject :exec
UPDATE projects SET name=?, priority=?, start_date=?, end_date=?, status=?, static_info=?, dynamic_info=? WHERE id=?
`

type UpdateProjectParams struct {
	Name        string
	Priority    int64
	StartDate   string
	EndDate     sql.NullString
	Status      string
	StaticInfo  string
	DynamicInfo string
	ID          int64
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) error {
	_, err := q.db.ExecContext(ctx, updateProject,
		arg.Name,
		arg.Priority,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.StaticInfo,
		arg.DynamicInfo,
		arg.ID,
	)
	return err
}
