// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const addTaskDependency = `-- name: AddTaskDependency :exec
INSERT OR IGNORE INTO task_dependencies (task_id, depends_on_id) VALUES (?, ?)
`

type AddTaskDependencyParams struct {
	TaskID      int64
	DependsOnID int64
}

func (q *Queries) AddTaskDependency(ctx context.Context, arg AddTaskDependencyParams) error {
	_, err := q.db.ExecContext(ctx, addTaskDependency, arg.TaskID, arg.DependsOnID)
	return err
}

const createTask = `-- name: CreateTask :execlastid
INSERT INTO tasks (project_id, meeting_id, title, start_date, deadline, estimated_hours, status, category, is_external, description)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskParams struct {
	ProjectID      int64
	MeetingID      sql.NullInt64
	Title          string
	StartDate      string
	Deadline       string
	EstimatedHours float64
	Status         string
	Category       string
	IsExternal     int64
	Description    string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createTask,
		arg.ProjectID,
		arg.MeetingID,
		arg.Title,
		arg.StartDate,
		arg.Deadline,
		arg.EstimatedHours,
		arg.Status,
		arg.Category,
		arg.IsExternal,
		arg.Description,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT t.id, t.project_id, t.meeting_id, t.title, t.start_date, t.deadline,
    t.estimated_hours, t.status, t.category, t.is_external, t.description,
    t.created_at, t.updated_at, p.name AS project_name,
    COALESCE(m.title, '') AS meeting_title
FROM tasks t
JOIN projects p ON p.id = t.project_id
LEFT JOIN meetings m ON m.id = t.meeting_id
WHERE t.id = ?
`

type GetTaskByIDRow struct {
	ID             int64
	ProjectID      int64
	MeetingID      sql.NullInt64
	Title          string
	StartDate      string
	Deadline       string
	EstimatedHours float64
	Status         string
	Category       string
	IsExternal     int64
	Description    string
	CreatedAt      string
	UpdatedAt      string
	ProjectName    string
	MeetingTitle   string
}

func (q *Queries) GetTaskByID(ctx context.Context, id int64) (GetTaskByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i GetTaskByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MeetingID,
		&i.Title,
		&i.StartDate,
		&i.Deadline,
		&i.EstimatedHours,
		&i.Status,
		&i.Category,
		&i.IsExternal,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectName,
		&i.MeetingTitle,
	)
	return i, err
}

const getTaskDependencies = `-- name: GetTaskDependencies :many
SELECT t.id, t.title, t.status
FROM task_dependencies td
JOIN tasks t ON t.id = td.depends_on_id
WHERE td.task_id = ?
`

type GetTaskDependenciesRow struct {
	ID     int64
	Title  string
	Status string
}

func (q *Queries) GetTaskDependencies(ctx context.Context, taskID int64) ([]GetTaskDependenciesRow, error) {
	rows, err := q.db.QueryContext(ctx, getTaskDependencies, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTaskDependenciesRow{}
	for rows.Next() {
		var i GetTaskDependenciesRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT t.id, t.project_id, t.meeting_id, t.title, t.start_date, t.deadline,
    t.estimated_hours, t.status, t.category, t.is_external, t.description,
    t.created_at, t.updated_at, p.name AS project_name,
    COALESCE(m.title, '') AS meeting_title,
    CASE WHEN t.deadline < date('now') AND t.status NOT IN ('done','cancelled') THEN 1 ELSE 0 END AS is_overdue
FROM tasks t
JOIN projects p ON p.id = t.project_id
LEFT JOIN meetings m ON m.id = t.meeting_id
WHERE (?1 IS NULL OR t.project_id = ?1)
  AND (?2 IS NULL OR t.status = ?2)
  AND (?3 IS NULL OR t.category = ?3)
  AND (?4 IS NULL OR (t.deadline < date('now') AND t.status NOT IN ('done','cancelled')))
ORDER BY t.deadline ASC, t.status ASC
`

type ListTasksParams struct {
	ProjectID interface{}
	Status    interface{}
	Category  interface{}
	Overdue   interface{}
}

type ListTasksRow struct {
	ID             int64
	ProjectID      int64
	MeetingID      sql.NullInt64
	Title          string
	StartDate      string
	Deadline       string
	EstimatedHours float64
	Status         string
	Category       string
	IsExternal     int64
	Description    string
	CreatedAt      string
	UpdatedAt      string
	ProjectName    string
	MeetingTitle   string
	IsOverdue      int64
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, listTasks,
		arg.ProjectID,
		arg.Status,
		arg.Category,
		arg.Overdue,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksRow{}
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.MeetingID,
			&i.Title,
			&i.StartDate,
			&i.Deadline,
			&i.EstimatedHours,
			&i.Status,
			&i.Category,
			&i.IsExternal,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectName,
			&i.MeetingTitle,
			&i.IsOverdue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByMeeting = `-- name: ListTasksByMeeting :many
SELECT t.id, t.title, t.deadline, t.status, t.category
FROM tasks t WHERE t.meeting_id = ?
ORDER BY t.deadline ASC
`

type ListTasksByMeetingRow struct {
	ID       int64
	Title    string
	Deadline string
	Status   string
	Category string
}

func (q *Queries) ListTasksByMeeting(ctx context.Context, meetingID sql.NullInt64) ([]ListTasksByMeetingRow, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByMeeting, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksByMeetingRow{}
	for rows.Next() {
		var i ListTasksByMeetingRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Deadline,
			&i.Status,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTaskDependency = `-- name: RemoveTaskDependency :exec
DELETE FROM task_dependencies WHERE task_id = ? AND depends_on_id = ?
`

type RemoveTaskDependencyParams struct {
	TaskID      int64
	DependsOnID int64
}

func (q *Queries) RemoveTaskDependency(ctx context.Context, arg RemoveTaskDependencyParams) error {
	_, err := q.db.ExecContext(ctx, removeTaskDependency, arg.TaskID, arg.DependsOnID)
	return err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks SET project_id=?, meeting_id=?, title=?, start_date=?, deadline=?,
    estimated_hours=?, status=?, category=?, is_external=?, description=?
WHERE id=?
`

type UpdateTaskParams struct {
	ProjectID      int64
	MeetingID      sql.NullInt64
	Title          string
	StartDate      string
	Deadline       string
	EstimatedHours float64
	Status         string
	Category       string
	IsExternal     int64
	Description    string
	ID             int64
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateTask,
		arg.ProjectID,
		arg.MeetingID,
		arg.Title,
		arg.StartDate,
		arg.Deadline,
		arg.EstimatedHours,
		arg.Status,
		arg.Category,
		arg.IsExternal,
		arg.Description,
		arg.ID,
	)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks SET status = ? WHERE id = ?
`

type UpdateTaskStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskStatus, arg.Status, arg.ID)
	return err
}
